[theme]
primaryColor = "#E11B22"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F4F6"
textColor = "#1F2937"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
